### ISSUE TITLE
USTVGO TVGUIDE 

### ISSUE THREAD

**Issue by t3chguru36** [interlark/ustvgo-iptv#20]
thank you for your work could you also create a python script that would pull the guide data from ustvgo and create a xml file I tried to use webgrabplus but they want to charge monthly and the ustvgo.tv.ini file is encrypted and needs a decrypt code before there script will pull the information I found another xml file online that host most of the channels but not all

**Comment by t3chguru36** [comment]
Yes I knew about the national.json file but I dont know how to convert it to appropriate xml file I found a software program called mc2xml that can pull channel listings from websites some are paid but there are also free ones im currently using dish network guide listings but when it generates a valid xml file and I use it once again not all channels are showing listings and I dont know why but im just going to use it

**Comment by interlark** [comment]
Code has been rewritten, now you can find [tvguide branch](https://github.com/interlark/ustvgo-iptv/tree/tvguide) which is responsible for regular update of following TV Guide EPG XML files:
  - 🔗 [XML EPG for IPTV players with light UI theme](https://raw.githubusercontent.com/interlark/ustvgo-iptv/tvguide/ustvgo.for-light-bg.xml)
  - 🔗 [XML EPG for IPTV players with dark UI theme](https://raw.githubusercontent.com/interlark/ustvgo-iptv/tvguide/ustvgo.for-dark-bg.xml)

 You can use them watching IPTV.
