### ISSUE TITLE
Can't view any vipStream streams

### ISSUE THREAD

**Issue by jgomez177** [interlark/ustvgo-iptv#24]
Just installed this but having an issue with any of the vipStreams (non VPN stream work fine)
I can see that my VPN is working as I can view the streams natively from the USTVGO url.
And I see in the logs that it is pulling the auth key but the streams are not working with a 403 Forbidden msg

Current setup is through a NordVPN Docker service another docker container running a ubuntu-desktop image

**Comment by interlark** [comment]
Yeah, I can reproduce it, look at it later.
