### ISSUE TITLE
Youtube Tutorial?

### ISSUE THREAD

**Issue by ollt51** [interlark/ustvgo-iptv#32]
is there a youtube tutorial on how to set this up? i am terrible at setting these type of things up and each time i try using the project it wont work

**Comment by interlark** [comment]
You can download latest app from [Release](https://github.com/interlark/ustvgo-iptv/releases/latest), open it and click "Start".
Is that what you mean?

**Comment by ollt51** [comment]
i tried it again but what do i do with the links after i press start? when i click on them it just takes me to text

**Comment by ollt51** [comment]
actually i think i know how i am supposed to do this now ill come back in a bit to tell you if i got it working or not

**Comment by ollt51** [comment]
I want to use the Jellyfin media player but it wont work for me

**Comment by ollt51** [comment]
i got it working with vlc but whenever i try to use something that supports the tv guide it doesnt work, it says i have to start a jellyfin server which i have no idea on how to do

**Comment by interlark** [comment]
Indeed [Jellyfin Media Player](https://github.com/jellyfin/jellyfin-media-player) is just a client for [Jellyfin](https://github.com/jellyfin/jellyfin), so you have to setup it first.
They have great installation and usage [documentation](https://jellyfin.org/docs/) for any OS you can follow.

I don't remember anything tricky during installation, you just download it, run, add playlist `m3u8` and EPG `xml` links, set update period for EPG and that's it.

```
1) Settings -> Dashboard -> Live TV -> Tuner Devices -> Add -> M3U Tuner -> URL -> http://127.0.0.1:6363/ustvgo.m3u8
2) Settings -> Dashboard -> Live TV -> TV Guide Data Providers -> Add -> XMLTV -> URL -> http://127.0.0.1:6363/tvguide.xml
3) Settings -> Dashboard -> Scheduled Tasks -> Live TV -> Refresh Guide -> Task Triggers -> "Every 30 minutes"
```

PS. You can use [IPTVNator](https://github.com/4gray/iptvnator) as it's easier to setup and has EPG.

**Comment by interlark** [comment]
I think [README](https://github.com/interlark/ustvgo-iptv/blob/master/README.md)'s manual is enough to install and run the app, if you would like to record a youtube video, I don't mind.
