### ISSUE TITLE
Two new channels added how to have ustvgo-iptv pick them up

### ISSUE THREAD

**Issue by yarafie** [interlark/ustvgo-iptv#33]
Two new channels added how to have ustvgo-iptv pick them up?

    79. Reelz Channel

    90. TeenNick

**Comment by interlark** [comment]
Thanks for the update. Added with the following changes.
I should release v0.1.8 with these new 2 channels later this day.
https://github.com/interlark/ustvgo-iptv/commit/60a8f8709d5a18771c25137a2868e51bf6a3d328
https://github.com/interlark/ustvgo-tvguide/commit/bafa2b64804957c29db199915315966a80ba0de5
https://github.com/interlark/ustvgo-tvguide/commit/2b1ccb3f05c07a38ad4581555ad98705e0c8cb8c

**Comment by interlark** [comment]
v0.1.8 with new channels released.
