### ISSUE TITLE
Tags for New, Live and Premiere

### ISSUE THREAD

**Issue by scmandias** [interlark/ustvgo-iptv#39]
Is it possible to scrape the info into xml file if a show is New, Live or a Premiere? Looking to record shows if they are new instead of manually recording.

**Comment by interlark** [comment]
Could you tell me what player or recorder do you use to track such tags?

**Comment by scmandias** [comment]
Yes I use ChannelsDVR. I can create a "series pass" that when it pick up the new tag in the guide it automatically records the show.

**Comment by interlark** [comment]
Could you provide a link where I can get it for Linux or Windows?
I don't usually record IPTV and not familiar with all these software.

I've heard that some EPG could contain programmes with special attribute "NEW", but I never seen yet a player that would show such attributes or count on them.

I could take such "NEW" tags from [TVGuide](https://www.tvguide.com/listings/) for example, but I'm not sure how to test it as I don't know software that could see such tags.

**Comment by scmandias** [comment]
Unfortunately it is a pay app through Google Play Store or Apple App Store. And you need a server setup with Windows, Linux or RPI4.

**Comment by interlark** [comment]
Ok, let's go other way. Could you give me an example of EPG XML guide file with such tags that correctly parsed by ChannelsDVR?

**Comment by scmandias** [comment]
I can't get the program header and footer to show but here are the tags
` 
<programme start="20220911190000 +0000" stop="20220911210000 +0000" channel="5.1">
 
    <title>2022 WNBA Finals</title>
    <sub-title>Connecticut Sun at Las Vegas Aces</sub-title>
    <desc>The Aces host the Sun for Game 1 of the WNBA Finals. Las Vegas won the regular-season series 2-1.</desc>
    <category>Sports</category>
    <category>Sports event</category>
    <category></category>
    <category></category>
    <category>Playoff sports</category>
    <category>Basketball</category>
    <icon src="https://tmsimg.fancybits.co/assets/p22507082_b_h9_ad.jpg?w=720&amp;h=540"></icon>
    <series-id system="tms">22507082</series-id>
    <episode-num system="tms">EP043652700001</episode-num>
    <new></new>
    <live></live>
    <video>
      <quality>HDTV</quality>
    </video>
  </programme>`

**Comment by interlark** [comment]
I've added "new" tags for new programs. https://github.com/interlark/ustvgo-tvguide/commit/1fb6203f28ce0146c8b35f56ead7985bcf92aef2
Could you check if it solves your problem with recording new shows?

Example:
```xml
  <programme start="20220912220000 +0000" stop="20220912230000 +0000" channel="CNBC">
    <title lang="en">Mad Money</title>
    <desc>Colorful financial analyst Jim Cramer offers his insights into the market.</desc>
    <category>Talk</category>
    <category>Business</category>
    <category>Business &amp; Finance</category>
    <category>Finance</category>
    <category>Trading</category>
    <category>Investment</category>
    <category>Stock markets</category>
    <icon src="https://raw.githubusercontent.com/interlark/ustvgo-tvguide/master/images/posters/provider/1/1/1-172509905.jpg" width="540" height="720"/>
    <icon src="https://raw.githubusercontent.com/interlark/ustvgo-tvguide/master/images/posters/provider/1/5/1-7530685391.jpg" width="720" height="405"/>
    <episode-num system="onscreen">S--E00</episode-num>
    <new/>
  </programme>
```

**Comment by interlark** [comment]
Also I've added 'live' tags for live events. https://github.com/interlark/ustvgo-tvguide/commit/2e553403d96a326b578e5954efc175444e060b99
If it works OK on popular players (I've tested only on IPTVNator), I'd keep these tags.

Example:
```xml
  <programme start="20220912220000 +0000" stop="20220913000000 +0000" channel="ESPN">
    <title lang="en">Monday Night Countdown</title>
    <desc>Suzy Kolber hosts a comprehensive preview of the NFL's weekly finale, featuring studio analysis and on-site reports, plus a weekend recap. Steve Young, Randy Moss and Booger McFarland and Adam Schefter round out the cast.</desc>
    <credits>
      <commentator>Rick Reilly</commentator>
    </credits>
    <category>Sports stuff</category>
    <category>Pro</category>
    <category>Football</category>
    <icon src="https://raw.githubusercontent.com/interlark/ustvgo-tvguide/master/images/posters/provider/1/1/1-1805302225.jpg" width="480" height="720"/>
    <icon src="https://raw.githubusercontent.com/interlark/ustvgo-tvguide/master/images/posters/provider/1/1/1-1805302224.jpg" width="720" height="360"/>
    <episode-num system="onscreen">S--E00</episode-num>
    <live/>
  </programme>
```

**Comment by scmandias** [comment]
Works Perfect! Just tested it out and it did exactly what was needed. Thank you!
