### ISSUE TITLE
Is it possible 

### ISSUE THREAD

**Issue by skiely** [interlark/ustvgo-iptv#41]
Hello is it possible to have my PC at home with VPN pulling all the streams to that PC but be able to play it from another  house?

**Comment by interlark** [comment]
Sure, why not. If your PC at home (connected to VPN) is behind a router, you should Port Forward your public IP `<PUBLIC_IP:6464>` to your local PC IP `<LOCAL_IP:6464>` so you can access playlist with `http://<PUBLIC_IP:6464>/ustvgo.m3u8` via the internet.

1) Go router -> NAT -> Port Forward your 6464 port to your local PC IP say `192.168.0.2` or what's your local IP is.
2) Get your public IP, say it would be for example `82.196.11.17`.
3) Connect your local PC to a VPN, so all the traffic from your PC would go through the VPN.
4) Run `ustvgo-iptv`.
5) Watch your IPTV with `http://82.196.11.17:6464/ustvgo.m3u8` from the internet.

I think it should work.

**Comment by skiely** [comment]
That's so awesome! I used port 6363 & I'm all set up. I just have to try it later from my girlfriends house. Thanks for explaining 👍🏻
