### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by t3chguru36** [interlark/ustvgo-iptv#43]
an option to allow Authentication on this app would be nice

**Comment by interlark** [comment]
Hm, that's a nice idea. It would help you to have a private access to your app on a VPS.
I could add pre-defined access token to the URL, something like `http://<IP>:6363/<auth_token>/...`

**Comment by t3chguru36** [comment]
I created a password protected webpage with hls live streams from different sources including ustvgo and those html links are linked to my app but authentication tokens would be great so that not just anyone could connect to my app if they discovered the port number associated with it which is easy to do with a port scan

**Comment by paul19920801** [comment]
If you have this installed on a VPS. Simply download and install Zerotier, on both the VPS, and desktop on which you want to access USTVGO-IPTV, and you will have immediate and secure access to your channels. No need to port forward or anything like that.
