### ISSUE TITLE
VPN Extra Channels

### ISSUE THREAD

**Issue by MCTyler** [interlark/ustvgo-iptv#45]
I have a VPN installed, do I have to use their VPN to get the extra channels?

**Comment by interlark** [comment]
It depends on wether you can see extra channels on https://ustvgo.tv without Nord VPN.

**Comment by interlark** [comment]
Usually USTVGO provides extra channels only to the Nord VPN clients.

**Comment by MCTyler** [comment]
I got it working thru PIA VPN in a Docker container. Thanks!
