### ISSUE TITLE
cli option to start after openvpn service loaded

### ISSUE THREAD

**Issue by vortex91** [interlark/ustvgo-iptv#46]
I spend 3 hours trying to figureo out how to start from CLI  as service using sh and systemd only after open vpn loads that way the m3u8 file generated includes all 102 channels.  As of now my openvpn loads after so i only get 70 or so m3u8.  Any help/guidance would be appricated.

**Comment by vortex91** [comment]
k got the solution

path to location of config is /etc/systemd/system/ustvgo-iptv.service

modify it so that in UNIT you have

  GNU nano 6.2                                /etc/systemd/system/ustvgo-iptv.service                                         
[Unit]
Description=USTVGO Free IPTV
Wants=sys-devices-virtual-net-tun0.device
After=network.target sys-devices-virtual-net-tun0.device
StartLimitInterval=0

this will wait for openvpn to load before starting up ustvgo-iptv

**Comment by interlark** [comment]
Yup, that line would do the trick.
```
After=network.target sys-devices-virtual-net-tun0.device
```
