### ISSUE TITLE
Custom issue 

### ISSUE THREAD

**Issue by theplexguy** [interlark/ustvgo-iptv#48]
While I'm new to code and such Ill try and explain the issue the best I can.
Im using Mac OS Monterey version 12.3.1
When I play any stream after getting the needed m3u8 urls It loads for 5ish seconds loads a frame of the show then nothing loads.
Ive trouble shooter with different players on different devices at most I can get a show to play 5 seconds.
What I think is causing it is a authentication error of sorts. When looking at the logs it creates a new authenticity key every 5 seconds or so when trying to play something so I think its trying to play then has to get re authenticated and fails.

**Comment by interlark** [comment]
1. This happens with all of the channels?
2. How do you run the script?
3. Place a part of your logs here.
4. Do you use VPN?
