### ISSUE TITLE
USTVGO-IPTV Terminates without request

### ISSUE THREAD

**Issue by paul19920801** [interlark/ustvgo-iptv#49]
Hi all. 

I run USTVGO-IPTV on my VPS, via secure connection, in which only I have access to. 

I am facing a strange issue, in which USTVGO-IPTV program terminates without warning, perhaps it could be related to inactivity, When accessing the playlist via Chrome after some time - I am faced with a ERR_CONNECTION_REFUSED on Chrome when I attempted to access the playlist. 

I created a new VPS connection, and moved USTV GO to there to see if perhaps I was running too many programs, and issues were arising, but this morning I woke up to exactly the same issue - It had terminated.

I have run --access-logs, and regenerated the playlist, and all is working for the timebeing, but only a matter of time before it terminates again, but will report output when I find something.

Thanks

**Comment by interlark** [comment]
Have you tried run ustvgo-iptv with the docker?
Docker restarts the container when it terminates for some reason.
