### ISSUE TITLE
Playback Error

### ISSUE THREAD

**Issue by smellyboot90** [interlark/ustvgo-iptv#51]
"This client isn't compatible with the media and the server isn't sending a compatible media format."

Im using Jellyfin and Docker

**Comment by interlark** [comment]
I've just run Jellyfin for testing purpose in a Docker container
```bash
docker run -d \
  --name=jellyfin \
  --rm \
  --network host \
  -v /opt/jellyfin/library:/config \
  -v /opt/jellyfin/tvseries:/data/tvshows \
  -v /opt/jellyfin/movies:/data/movies \
  lscr.io/linuxserver/jellyfin:latest
```
Then I added M3U playlist 
```
Administration -> Dashboard -> Live TV -> Tuner Devices -> Add -> M3U Tuner -> URL -> http://127.0.0.1:6363/ustvgo.m3u8
```
And XML TV Guide
```
Administration -> Dashboard -> Live TV -> TV Guide Data Providers -> XMLTV -> URL -> http://127.0.0.1:6363/tvguide.xml
```
After that I could go home page and ran any channel without any trouble.

Have you tried analyze Jellyfin's logs?

**Comment by smellyboot90** [comment]
yeah i tried to look at the logs and it seems pretty normal, it gives me the links for the iptv and then when i try to connect to a channel it says  `[No VIP (No VPN)] Fetching new auth key from USTVGO.` then it gets a auth key but it still says it isnt compatiable 

ive tried to setup the entire thing again and it still did the same thing and i used to use VLC before i found out how to use jellyfin and i tried connecting on there which i knew how to and it said the same thing

**Comment by interlark** [comment]
Is your ustvgo-iptv server also inside a docker container?

**Comment by smellyboot90** [comment]
yeah im running the server in the docker container but im using the tray app for jellyfin

**Comment by interlark** [comment]
So, everything in docker containers and still you got an issue, that's interesting.

If I were you, I would run Jellyfin and check up those URLs which make Jellyfin argue about its content.
I bet you can get them from the log file or stout.

Once you know the responses content, you would get a clue to the issue.

**Comment by smellyboot90** [comment]
i couldnt find anything in the logs but when i went to the ustvgo website to try to watch there it never worked either or only worked for a few minutes

but alot of things have stopped working on my computer like multiplayer games i cant join and most things i cant use without a vpn so i connected to my vpn and used the ustvgo gui and it works
