### ISSUE TITLE
Windows GUI Startup

### ISSUE THREAD

**Issue by Erson33** [interlark/ustvgo-iptv#53]
Hello,

I have set the program to run at startup however it would be great if it could be set to automatically "Start" the process at program launch. 

Thanks

**Comment by nater1983** [comment]
what kinda of system do you have an sysvinit or systemd?

**Comment by Erson33** [comment]
Hello, thank you for the reply.

I'm running the program on Windows, specifically the Windows GUI. I have the application set to run on start-up however this merely opens the application - it doesn't initiate the process of compiling the m3u.

**Comment by nater1983** [comment]
I think that would be because the appliication doesn't have the necessary code to have it initiate the process of compling on start up of you Windows machine.
On Linux we have multiple ways to make ustvgo start up with the system booting. Sysvinit,Systemd etc..

**Comment by Erson33** [comment]
Ah okay, I suppose I prefer that answer to me having missed something (I'm quite new to all of this).

It sure would be a helpful feature - I wonder if it can be implemented in the future.

**Comment by kblair1** [comment]
Load python on your Windows machine, it's part of the windows applications. Use the START python app from the CLI inst. to install the USTVGO program then run the python app for ustvgo. You can run it from a batch file to auto start. It will start in a cmd window. You can add a pause statement at the end of bat to see the results of the bat. Leave the cmd window open during operation. Note do not use localhost ip or logo icons will not show on external devices. Get Outlook for AndroidFrom: Erson33 ***@***.***>Sent: Thursday, November 24, 2022, 7:45 AMTo: interlark/ustvgo-iptv ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [interlark/ustvgo-iptv] Windows GUI Startup (Issue #53)
Ah okay, I suppose I prefer that answer to me having missed something (I'm quite new to all of this).
It sure would be a helpful feature - I wonder if it can be implemented in the future.

**Comment by Erson33** [comment]
Thank you!

It's been an adventure but I think I have it all sorted - really appreciate the reply and the help!
