### ISSUE TITLE
Add more VPN providers

### ISSUE THREAD

**Issue by papampi** [interlark/ustvgo-iptv#54]
Is it possible to add more VPN providers like expressvpn to unlock more channels?

**Comment by interlark** [comment]
Add to what? You can use whatever VPN provider you want, as I know USTVGO wants you to have US IP, just get any US VPN.

**Comment by papampi** [comment]
For vip streams, only Nord activate VIP

**Comment by interlark** [comment]
I see, looks like any *US VPN* opens *NO-VIP* channels, and *Nord VPN* opens *VIP* channels.
Since this summer they closed *NO-VIP* channels for non-US viewers.
