### ISSUE TITLE
Script updated 

### ISSUE THREAD

**Issue by skiely** [interlark/ustvgo-iptv#56]
Hi don't know if you know. Ben moose updated the script to work without USA VPN.
Also apparently filmon is back working & he's bringing back TVMUCHO.
It'd be great to get filmon & TVMUCHO the interlark treatment 👍🏻🤞🏻

**Comment by interlark** [comment]
Hi, I doubt that you can fool server-side IP check ups, the only way to watch the full list of the channels is to get US VPN or use similar servies, like [123tv](https://github.com/interlark/123tv-iptv).
