### ISSUE TITLE
HD feeds

### ISSUE THREAD

**Issue by rffalcon77** [interlark/ustvgo-iptv#57]
No issue.  USTVGO has added some HD feeds of ESPN, ABC, CBS, NBC, FOX, HBO, FS1, CW, NFL NETWORK.  It would be great if those could be added.  Thanks for your consideration.

**Comment by interlark** [comment]
Thank you for the update, I'll look at it soon.

**Comment by rffalcon77** [comment]
Thank you Andy!

Happy New Year!

**Comment by rffalcon77** [comment]
Hey Interlark,

Hold off on the HD channel update for USTVGO for now.  A lot of chatter on
their discord of issues on the the HD channels and they commented that they
are aware and working on a fix.

Hate to have you put time into something they end up pulling back on.

**Comment by NukeBringer87** [comment]
I'm very excited about the new HD channels! integration into the software would be awesome!

Thanks for the hard work on this!
Please keep us posted if you decide to add HD channel support!

**Comment by dmitryfd** [comment]
I wrote a quick script to fetch the updated list of all channels (incl. HD ones):
https://gist.github.com/dmitryfd/3a96e15364525f176ab1255bdd5df6ef

Some minor edits might be needed wrt categories etc, but should be most of the way there 👍

**Comment by NukeBringer87** [comment]
Thank you!
Could you provide some documentation on how to implement this?

**Comment by dmitryfd** [comment]
> Thank you! Could you provide some documentation on how to implement this?

What I did is launch `ustvgo.py` from source code (rather than `pip` or GUI) and replaced bundled `channels.json` file with mine. The HD streams seem to be working great (with an aside that they require NordVPN), but more poking needs to be done for them to show up correctly in the Guide.

**Comment by dmitryfd** [comment]
> but more poking needs to be done for them to show up correctly in the Guide.

Seems like that requires editing `channels.json` in [this repo](https://github.com/interlark/ustvgo-tvguide/blob/master/channels.json) as well. 

Maybe @interlark can update them in one swoop, or I can get the pull requests going in the coming days.

Until then, happy new year y'all!

**Comment by yarafie** [comment]
Great work. I was looking into this myself and the channels.json are identical in this repository and the tvguide repository. Also some changes into the icon for each channel in the epg repository will need to be done its in a directory somewhere

**Comment by SuperstationWTF** [comment]
dmitryfd It works! A Festivus Miracle. As noted, just missing some chanell icons but that is not important.  And all 113 channels!

**Comment by dmitryfd** [comment]
As promised, #59 is ready for review/merge.

I've also opened an equivalent PR (incl. icons) in the other repo: https://github.com/interlark/ustvgo-tvguide/pull/3

**Comment by rffalcon77** [comment]
Sounds like the issues are resolved now.  They even added another channel,
Discovery Family.

Thank you again for your great talents!

**Comment by dmitryfd** [comment]
Added DiscoveryFamily to my PRs.
@interlark, could you please review?

**Comment by interlark** [comment]
New channels are available in [v0.1.12](https://github.com/interlark/ustvgo-iptv/releases/tag/v0.1.12). Thanks, everybody!

**Comment by rffalcon77** [comment]
Awesome!

Thank you!
