### ISSUE TITLE
Failed to start ustvgo-iptv.service: Unit ustvgo-iptv.service not found. Yet 123tv-iptv loads without issue

### ISSUE THREAD

**Issue by Nostradamus1973** [interlark/ustvgo-iptv#58]
Fresh install and I get this error:
Failed to start ustvgo-iptv.service: Unit ustvgo-iptv.service not found
I have 123tv installed without any issues. I've uninstalled and reinstalled(ustvgo) a dozen times with the same result and it's making me insane!
Please help

Thank you

**Comment by Nostradamus1973** [comment]
Nevermind, I fixed it, unfortunately I don't know what I did.
Happy New Year Andy and sorry for the trouble.
Problem solved
Thx

**Comment by Nostradamus1973** [comment]
Good morning Andy,
Do I have to input the proper directory when using the command you supplied: sudo -E env "PATH=$PATH" ustvgo-iptv install-service
I can't remember if I had changed these values before.
Thx again Andy

**Comment by interlark** [comment]
You don't need to input anything, the command for installing the service is `sudo -E env "PATH=$PATH" ustvgo-iptv install-service` or just simply use the Docker command.

I'm glad you fixed your problems :)
